# Arrow Pattern
print(" "*5 + "*")
print(" "*4 + "*"*2)
print(" "*3 + "*"*3)
print(" "*2 + "*"*4)
print(" " + "*"*5)
print(" " + "*"*5)
print(" "*2 + "*"*4)
print(" "*3 + "*"*3)
print(" "*4 + "*"*2)
print(" "*5 + "*")
print(" "*19 + "*"*1)
print("*"*20)
print(" "*19 + "*"*1)
print(" "*5 + "*")
print(" "*4 + "*"*2)
print(" "*3 + "*"*3)
print(" "*2 + "*"*4)
print(" " + "*"*5)
print(" " + "*"*5)
print(" "*2 + "*"*4)
print(" "*3 + "*"*3)
print(" "*4 + "*"*2)
print(" "*5 + "*")

