print("----------------------------------------------------------------------------------")
print("                 Python IDE Comparison Table")
print("----------------------------------------------------------------------------------")
print("IDE Name        Speed       Type              Debugging       Best For")
print("----------------------------------------------------------------------------------")
print("IDLE            Fast        Beginner IDE      Basic           Learning Python")
print("VS Code         Very Fast   Code Editor       Advanced        Web Development")
print("PyCharm         Medium      Professional IDE  Very Advanced   Large Projects")
print("Jupyter         Fast        Notebook IDE      Basic           Data Science & ML")
print("----------------------------------------------------------------------------------")